// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tennishallen.Data;

#nullable disable

namespace Tennishallen.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tennishallen.Data.Models.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("Tennishallen.Data.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = 1,
                            UserId = new Guid("88605bf0-bdd3-45b7-8d7f-5fd8426212ff")
                        },
                        new
                        {
                            Id = 2,
                            Name = 0,
                            UserId = new Guid("df7d2185-899d-481f-83db-cc9e1c97753c")
                        },
                        new
                        {
                            Id = 3,
                            Name = 0,
                            UserId = new Guid("8e454215-eb40-493e-bd0f-c6c876016425")
                        },
                        new
                        {
                            Id = 4,
                            Name = 0,
                            UserId = new Guid("9decae06-d0ee-4081-ae4a-59648730ba4d")
                        },
                        new
                        {
                            Id = 5,
                            Name = 0,
                            UserId = new Guid("8bb581f0-f2f5-463a-8c66-1008ee947271")
                        });
                });

            modelBuilder.Entity("Tennishallen.Data.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CourtId1")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("CourtId1");

                    b.HasIndex("MemberId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Tennishallen.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HourlyWage")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88605bf0-bdd3-45b7-8d7f-5fd8426212ff"),
                            Active = true,
                            Address = "Tennisstraat 1",
                            Birthdate = new DateOnly(1, 1, 1),
                            City = "Hengelo",
                            Email = "r.vandongen@tennishallenhengelo.nl",
                            FirstName = "Richard",
                            HourlyWage = 0.0,
                            LastName = "van Dongen",
                            Password = "$2a$10$2IrWj2.r72iMrwkk4Bja/uWQbjaTV27OMSFIpfc1afX3t.eQLMZR2",
                            Phone = "06 12345678",
                            PostalCode = "1234TB"
                        },
                        new
                        {
                            Id = new Guid("df7d2185-899d-481f-83db-cc9e1c97753c"),
                            Active = true,
                            Address = "Tennisstraat 2",
                            Birthdate = new DateOnly(1, 1, 1),
                            City = "Hengelo",
                            Email = "B.Hand@tennishallenhengelo.nl",
                            FirstName = "Beck",
                            HourlyWage = 0.0,
                            LastName = "Hand",
                            Password = "$2a$10$ugEr.WK1ypE0bU6aHK1ISuT33VX7n43AMrjKWZV6dXgMG60Mp50dm",
                            Phone = "06 55334567",
                            PostalCode = "1234TB"
                        },
                        new
                        {
                            Id = new Guid("8e454215-eb40-493e-bd0f-c6c876016425"),
                            Active = true,
                            Address = "Tennisstraat 3",
                            Birthdate = new DateOnly(1, 1, 1),
                            City = "Hengelo",
                            Email = "G.Slam@tennishallenhengelo.nl",
                            FirstName = "Grant",
                            HourlyWage = 0.0,
                            LastName = "Slam",
                            Password = "$2a$10$QJQUmIFsz1L/U9qiD64YAOpw6M4p9ay04.NKIczdSYSW/qy0R.7Du",
                            Phone = "06 67316808",
                            PostalCode = "1234TB"
                        },
                        new
                        {
                            Id = new Guid("9decae06-d0ee-4081-ae4a-59648730ba4d"),
                            Active = true,
                            Address = "Tennisstraat 4",
                            Birthdate = new DateOnly(1, 1, 1),
                            City = "Hengelo",
                            Email = "T.Ishbahl@tennishallenhengelo.nl",
                            FirstName = "Tehn",
                            HourlyWage = 0.0,
                            LastName = "Ishbahl",
                            Password = "$2a$10$WtOo1xjQPsLon5y3qC4Kh.bcaXlgM6xltGOvvxB6PUkm3nDKObOuO",
                            Phone = "06 17884958",
                            PostalCode = "1234TB"
                        },
                        new
                        {
                            Id = new Guid("8bb581f0-f2f5-463a-8c66-1008ee947271"),
                            Active = true,
                            Address = "Tennisstraat 5",
                            Birthdate = new DateOnly(1, 1, 1),
                            City = "Hengelo",
                            Email = "C.Racket@tennishallenhengelo.nl",
                            FirstName = "Courtney",
                            HourlyWage = 0.0,
                            LastName = "Racket",
                            Password = "$2a$10$bArkXdRVH7iLyz0894lNVOjv4UAHQgNhrINeaNSBGyYUQh83Ys8/G",
                            Phone = "06 94685537",
                            PostalCode = "1234TB"
                        });
                });

            modelBuilder.Entity("Tennishallen.Data.Models.Group", b =>
                {
                    b.HasOne("Tennishallen.Data.Models.User", "User")
                        .WithMany("Groups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tennishallen.Data.Models.Reservation", b =>
                {
                    b.HasOne("Tennishallen.Data.Models.User", "Coach")
                        .WithMany("CoachReservations")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tennishallen.Data.Models.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId1");

                    b.HasOne("Tennishallen.Data.Models.User", "Member")
                        .WithMany("MemberReservations")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Court");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Tennishallen.Data.Models.User", b =>
                {
                    b.Navigation("CoachReservations");

                    b.Navigation("Groups");

                    b.Navigation("MemberReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
